### ISSUE TITLE
Crashloop on a server

### ISSUE THREAD

**Issue by JWTHDYTWA** [Natanaelel/BankStorage#45]
**Mod version**
1.4.4

**Describe the bug**
I'm stuck in a crash loop on a server.

**To Reproduce**
1. Idk, it just occurred at some point

**Logs**
[Crash report](https://gist.github.com/JWTHDYTWA/dac2b338942b54158ccdd83228dee8b7)
[Latest.log](https://gist.github.com/JWTHDYTWA/ffb90d5f66fd578d5af366440a8854a8)

**Additional context**
I'm playing on **TNP Limitless 8** modpack.
The crash report is saying that Bank Storage is the cause. It also refers to Industrial Foregoing, but Bank storage is in the header.

**Comment by Natanaelel** [comment]
Bridging mod is at fault here. I'll open an issue.

**Comment by Natanaelel** [comment]
Should be fixed in bridging mod. Watch for updates.

**Comment by JWTHDYTWA** [comment]
Still an issue: https://github.com/squeeglii/BridgingMod/issues/34#issuecomment-2692657519
